name: 'Linear task action'
description: 'Creates a linear task and returns its id'
author: 'opera-joakimd'
inputs:
  key:
    required: true
    description: 'Linear api key'
  team_name:
    required: true
    description: 'Linear team name'
  title:
    required: true
    description: 'Title of the linear task that should be created'
outputs:
  task_id:
    description: 'Id of the created task'
runs:
  using: 'node16'
  main: 'dist/index.js'
